name: AWS-RDP
name: AWS-VPS

on: workflow_dispatch

@@ -11,8 +11,8 @@ jobs:
    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-RDP/main/ngrok-stable-windows-amd64.zip -/path/to/ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-RDP/main/start.bat /path/to/ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-VPS/main/ngrok-stable-windows-amd64.zip /path/to/ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-VPS/main/start.bat -/path/to/ngrok.zipt
    - name: Extracting ngrok Files.
      run: Expand-Archive /ngrok.zip
    - name: Connecting to your pablosolution account.
@@ -30,6 +30,5 @@ jobs:
      run: cmd /c start.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-RDP/main/loop.ps1 -OutFile loop.ps1
        Invoke-WebRequest https://raw.githubusercontent
